import Link from "next/link";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getOrganizationId } from "@/lib/organization";

export default async function DealsPage() {
  const session = await auth(); const organizationId = getOrganizationId(session!.user.id);
  const deals = await prisma.deal.findMany({ where: { organizationId, ...(session!.user.role === "FIELD_EXECUTIVE" ? { assignedToId: session!.user.id } : {}) }, include: { lead: { select: { clientName: true } }, property: { select: { title: true, propertyCode: true, inventorySource: true, partner: { select: { name: true } } } }, assignedTo: { select: { name: true } }, offers: { select: { amount: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 1 }, activities: { select: { createdAt: true }, orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" }, take: 100 });
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-[#1B2430]">Deals & Negotiations</h1><p className="mt-1 text-sm text-[#596579]">Internal negotiation pipeline. No payments are collected here.</p></div><div className="overflow-x-auto rounded-xl border border-[#E7ECF2]"><table className="w-full text-sm"><thead className="bg-[#FAFBFC] text-left text-[#596579]"><tr><th className="p-3">Client / Property</th><th className="p-3">Source</th><th className="p-3">Stage</th><th className="p-3">Latest offer</th><th className="p-3">Owner</th><th className="p-3">Activity</th></tr></thead><tbody>{deals.map(d => <tr key={d.id} className="border-t border-[#E7ECF2]"><td className="p-3"><Link className="font-medium text-blue-700" href={`/deals/${d.id}`}>{d.lead?.clientName ?? "Unassigned lead"}</Link><div className="text-xs text-[#596579]">{d.property?.propertyCode} · {d.property?.title}</div></td><td className="p-3">{d.property?.inventorySource ?? "—"}{d.property?.partner ? <div className="text-xs">{d.property.partner.name}</div> : null}</td><td className="p-3">{d.stage}</td><td className="p-3">{d.offers[0] ? `₹${d.offers[0].amount.toLocaleString("en-IN")}` : "—"}</td><td className="p-3">{d.assignedTo?.name ?? "—"}</td><td className="p-3">{d.activities[0]?.createdAt.toLocaleDateString() ?? "—"}</td></tr>)}</tbody></table></div></div>;
}
