-- Additive only (index creations - no table/column changes, no data
-- migration, safe to run without downtime on Postgres via a normal
-- migration; consider CREATE INDEX CONCURRENTLY instead if the leads/
-- properties tables are large in production at apply time, since a plain
-- CREATE INDEX takes a write lock on the table for the duration of the
-- build).
--
-- Generated by offline schema diff (prisma migrate diff
-- --from-schema-datamodel <pre-change schema> --to-schema-datamodel
-- prisma/schema.prisma --script) rather than `prisma migrate dev` because
-- no live/dev database was available in this environment - see the
-- performance audit report for the query evidence behind each index.
-- NOT applied to any database. For human review before deploying.
--
-- leads_organizationId_createdAt_idx: the main /leads list
-- (src/app/(app)/leads/page.tsx) - organizationId-scoped, paginated,
-- default-sorted newest-first. No existing index covered both the filter
-- and the sort together.
--
-- properties_createdAt_idx / leads_createdAt_idx: the default (no extra
-- filter) newest-first sort used by /properties, GET /api/properties, and
-- the dashboard's newLeadsToday count - none of those queries currently
-- carry an organizationId predicate (a separate, pre-existing
-- multi-tenancy gap noted in the audit but out of scope for this
-- performance-only change), so a plain index is what actually matches
-- the literal query shape today.
--
-- leads_assignedToId_idx: the dashboard's unassignedLeads count
-- (assignedToId: null, no organizationId predicate) - the existing
-- [organizationId, assignedToId] composite can't serve a query that never
-- supplies organizationId.
--
-- leads_status_updatedAt_idx: the dashboard's dealsClosedThisMonth count
-- (status = CLOSED_WON AND updatedAt >= start-of-month, no organizationId
-- predicate).

-- CreateIndex
CREATE INDEX "properties_createdAt_idx" ON "properties"("createdAt");

-- CreateIndex
CREATE INDEX "leads_organizationId_createdAt_idx" ON "leads"("organizationId", "createdAt");

-- CreateIndex
CREATE INDEX "leads_createdAt_idx" ON "leads"("createdAt");

-- CreateIndex
CREATE INDEX "leads_assignedToId_idx" ON "leads"("assignedToId");

-- CreateIndex
CREATE INDEX "leads_status_updatedAt_idx" ON "leads"("status", "updatedAt");
