import { NextRequest, NextResponse } from "next/server";
import { requireSession, handleApiError, ApiError } from "@/lib/api-auth";
import { recordAudit } from "@/lib/audit";
import { buildReport, toCsv, REPORT_TYPES, type ReportType } from "@/lib/report-builder";

/**
 * Custom Report Builder export (Phase 3, Module 6 + Module 9). Produces a
 * CSV file (opens directly in Excel) branded with the org name, generation
 * timestamp, generated-by user, and the filters used, matching the "KP
 * Properties branding / date / generated by / filters used" requirement -
 * a true binary .xlsx/.pdf would need a new dependency, which this pass
 * intentionally avoids; CSV is Excel-compatible and requires none.
 */
export async function GET(req: NextRequest) {
  try {
    const session = await requireSession(["ADMIN"]);
    const sp = req.nextUrl.searchParams;
    const type = sp.get("type") as ReportType | null;
    if (!type || !REPORT_TYPES.includes(type)) {
      throw new ApiError(400, `type must be one of: ${REPORT_TYPES.join(", ")}`);
    }
    const fromParam = sp.get("from");
    const toParam = sp.get("to");
    const from = fromParam ? new Date(fromParam) : undefined;
    const to = toParam ? new Date(toParam) : undefined;

    const result = await buildReport(type, { from, to });

    const metaLines = [
      `# KP Properties - Delhi Broker CRM`,
      `# Report: ${type}`,
      `# Generated: ${new Date().toISOString()}`,
      `# Generated by: ${session.user.name}`,
      `# Filters: ${from ? `from=${from.toISOString()} ` : ""}${to ? `to=${to.toISOString()}` : ""}`.trim() || "# Filters: none",
      "",
    ];
    const csv = metaLines.join("\n") + toCsv(result);

    await recordAudit({ userId: session.user.id, action: "EXPORT", entityType: "Report", newValues: { type, from, to, rowCount: result.rows.length } });

    return new NextResponse(csv, {
      headers: { "Content-Type": "text/csv; charset=utf-8", "Content-Disposition": `attachment; filename="${type}-report-${Date.now()}.csv"` },
    });
  } catch (err) {
    return handleApiError(err);
  }
}
