import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireSession, handleApiError } from "@/lib/api-auth";
import { getOrganizationId } from "@/lib/organization";
import { portalConnectionSchema } from "@/lib/validators";
import { recordAudit } from "@/lib/audit";

export async function GET() { try { const session = await requireSession(["ADMIN"]); const organizationId = getOrganizationId(session.user.id); const connections = await prisma.propertyPortalConnection.findMany({ where: { organizationId }, orderBy: { provider: "asc" } }); return NextResponse.json({ connections: connections.map(({ credentialReference: _secret, config: _config, ...safe }) => safe) }); } catch (err) { return handleApiError(err); } }
export async function POST(req: NextRequest) { try { const session = await requireSession(["ADMIN"]); const organizationId = getOrganizationId(session.user.id); const data = portalConnectionSchema.parse(await req.json()); const existing = await prisma.propertyPortalConnection.findFirst({ where: { organizationId, provider: data.provider, accountReference: data.accountReference ?? null } }); const connection = existing ? await prisma.propertyPortalConnection.update({ where: { id: existing.id }, data: { connectionMode: data.connectionMode, displayName: data.displayName, status: data.status } }) : await prisma.propertyPortalConnection.create({ data: { organizationId, ...data, config: "{}", createdById: session.user.id } }); await recordAudit({ userId: session.user.id, action: existing ? "UPDATE" : "CREATE", entityType: "PropertyPortalConnection", entityId: connection.id, newValues: { event: existing ? "PORTAL_CONNECTION_UPDATED" : "PORTAL_CONNECTION_CREATED", provider: data.provider, mode: data.connectionMode } }); const { credentialReference: _secret, config: _config, ...safe } = connection; return NextResponse.json({ connection: safe }, { status: existing ? 200 : 201 }); } catch (err) { return handleApiError(err); } }
