"use client";
import { useState } from "react";

const SIDES = ["CLIENT", "OWNER", "INVENTORY_PARTNER", "INTERNAL"] as const;
export function DealActions({ dealId, indirect, canManage }: { dealId: string; indirect: boolean; canManage: boolean }) {
  const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const [side, setSide] = useState<(typeof SIDES)[number]>("CLIENT"); const [lostReasonCategory, setLostReasonCategory] = useState("PRICE"); const [message, setMessage] = useState("");
  if (!canManage) return null;
  async function offer() { const r = await fetch(`/api/deals/${dealId}/offers`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ amount: Number(amount), side, note: note || null }) }); setMessage(r.ok ? "Offer recorded. Refresh to view the append-only timeline." : "Could not record offer."); }
  async function stage(next: string, extra: Record<string, string> = {}) { const r = await fetch(`/api/deals/${dealId}/stage`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ stage: next, notes: note || null, ...extra }) }); setMessage(r.ok ? "Stage updated. Refresh to view the latest state." : "Stage update was rejected."); }
  return <section className="rounded-xl border p-4 space-y-3"><h2 className="font-semibold">Negotiation actions</h2><div className="flex flex-wrap gap-2"><select value={side} onChange={e => setSide(e.target.value as typeof side)} className="border rounded px-2 py-1">{SIDES.filter(s => indirect || s !== "INVENTORY_PARTNER").map(s => <option key={s}>{s}</option>)}</select><input aria-label="Offer amount" value={amount} onChange={e => setAmount(e.target.value)} type="number" min="1" placeholder="Amount" className="border rounded px-2 py-1"/><button onClick={offer} className="rounded bg-blue-700 text-white px-3 py-1">Add {side.replace("_", " ")} offer</button></div><textarea aria-label="Internal note" value={note} onChange={e => setNote(e.target.value)} placeholder="Internal note / closure note" className="w-full border rounded p-2"/><div className="flex flex-wrap gap-2"><button onClick={() => stage("NEGOTIATION")} className="border rounded px-3 py-1">Start Negotiation</button><button onClick={() => stage("AGREEMENT")} className="border rounded px-3 py-1">Agreement Pending</button><button onClick={() => stage("CLOSED_WON")} className="border rounded px-3 py-1">Close Won</button><select aria-label="Lost reason" value={lostReasonCategory} onChange={e => setLostReasonCategory(e.target.value)} className="border rounded px-2 py-1"><option>PRICE</option><option>LOCATION</option><option>COMPETITION</option><option>BUDGET</option><option>OWNER_ISSUE</option><option>CLIENT_NOT_INTERESTED</option><option>OTHER</option></select><button onClick={() => stage("CLOSED_LOST", { lostReason: note || "Lost negotiation", lostReasonCategory })} className="border rounded px-3 py-1">Close Lost</button></div>{message && <p className="text-sm text-[#596579]">{message}</p>}</section>;
}
