"use client";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import type { PropertyPortalCapabilities, PropertyPortalProviderId } from "@/integrations/property-portals/registry";

type Connection = { provider: string; status: string; connectionMode: string; displayName: string | null; accountReference?: string | null; lastSyncAt: Date | string | null; lastSuccessfulSyncAt: Date | string | null; lastErrorSummary: string | null };
export function ConnectionCard({ provider, capabilities, initial, canEdit }: { provider: PropertyPortalProviderId; capabilities: PropertyPortalCapabilities; initial?: Connection; canEdit: boolean }) {
  const [editing, setEditing] = useState(false); const [connection, setConnection] = useState(initial); const [busy, setBusy] = useState(false);
  async function save(form: FormData) { setBusy(true); try { const response = await fetch("/api/integrations/property-portals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider, displayName: form.get("displayName") || undefined, accountReference: form.get("accountReference") || undefined, connectionMode: form.get("connectionMode"), status: form.get("status") }) }); if (!response.ok) throw new Error("Unable to save connection"); setConnection((await response.json()).connection); setEditing(false); } finally { setBusy(false); } }
  return <section className="rounded-2xl border border-[#E7ECF2] bg-white p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{provider.replaceAll("_", " ")}</h2><Badge tone={connection?.status === "DEGRADED" || connection?.status === "AUTH_FAILED" ? "red" : "blue"}>{(connection?.status ?? "NOT_CONFIGURED").replaceAll("_", " ")}</Badge></div>{editing ? <form action={save} className="mt-4 space-y-3 text-sm"><input name="displayName" defaultValue={connection?.displayName ?? ""} placeholder="Display name" className="w-full rounded border p-2" /><input name="accountReference" defaultValue={connection?.accountReference ?? ""} placeholder="Account reference (optional)" className="w-full rounded border p-2" /><select name="connectionMode" defaultValue={connection?.connectionMode ?? "MANUAL"} className="w-full rounded border p-2">{["API","WEBHOOK","CSV","EMAIL","MANUAL"].map(x => <option key={x}>{x}</option>)}</select><select name="status" defaultValue={connection?.status ?? "NOT_CONFIGURED"} className="w-full rounded border p-2">{["NOT_CONFIGURED","PARTNER_ACCESS_REQUIRED","CONNECTED","DEGRADED","AUTH_FAILED"].map(x => <option key={x}>{x.replaceAll("_", " ")}</option>)}</select><p className="text-xs text-[#596579]">Credentials are managed outside the CRM and are never accepted or displayed here.</p><div className="flex gap-2"><button disabled={busy} className="rounded bg-[#3366FF] px-3 py-2 text-white">{busy ? "Saving…" : "Save"}</button><button type="button" onClick={() => setEditing(false)} className="rounded border px-3 py-2">Cancel</button></div></form> : <><p className="mt-2 text-sm text-[#596579]">{connection ? `${connection.displayName ?? "Connection"} · ${connection.connectionMode}` : "No authorized connection configured"}</p><dl className="mt-4 space-y-1.5 text-xs text-[#596579]"><div>Lead ingestion: {capabilities.supportsLeadWebhook.replaceAll("_", " ")}</div><div>Listing sync: {capabilities.supportsListingPublish.replaceAll("_", " ")}</div><div>Residential / commercial: {capabilities.supportsResidential.replaceAll("_", " ")} / {capabilities.supportsCommercial.replaceAll("_", " ")}</div><div>Rent / sale: {capabilities.supportsRent.replaceAll("_", " ")} / {capabilities.supportsSale.replaceAll("_", " ")}</div>{connection?.lastSuccessfulSyncAt && <div>Last successful sync: {new Date(connection.lastSuccessfulSyncAt).toLocaleString("en-IN")}</div>}{connection?.lastErrorSummary && <div className="text-red-700">Last error: {connection.lastErrorSummary}</div>}</dl>{canEdit && <button onClick={() => setEditing(true)} className="mt-4 rounded border px-3 py-2 text-sm">{connection ? "Edit connection" : "Configure connection"}</button>}</>}</section>;
}
