"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCheck, Clock3, Link2, Loader2, MessageCircle, RefreshCw, Search, Send, UserRound } from "lucide-react";

type UserRole = "ADMIN" | "DATA_MANAGER" | "FIELD_EXECUTIVE";
type Conversation = { id: string; phoneNumber: string; displayName: string | null; contactState: "LINKED" | "UNKNOWN" | "AMBIGUOUS"; unreadCount: number; lastInboundAt: string | null; lastMessageAt: string | null; assignedToId: string | null; assignedTo: { id: string; name: string } | null; lead: { id: string; clientName: string; status: string; priority: string } | null; messages: Array<{ content: string; messageType: string; createdAt: string }> };
type Message = { id: string; direction: "INBOUND" | "OUTBOUND"; content: string; messageType: string; status: string; errorMessage: string | null; createdAt: string; mediaFilename: string | null; replyToMessage: { id: string; content: string } | null };
type Options = { leads: Array<{ id: string; clientName: string; phone: string; leadCode: string }>; employees: Array<{ id: string; name: string }>; catalogues: Array<{ id: string; title: string; leadId: string; version: number }>; properties: Array<{ id: string; title: string; area: string }>; templates: Array<{ name: string; useCase: string; approved: boolean; bodyTemplate?: string }>; provider: string };
type Detail = Conversation & { leadId: string | null; lastInboundAt: string | null; lead: (Conversation["lead"] & { requirementType: string; preferredLocation: string; catalogueShares: Array<{ version: number }>; visits: Array<{ visitDate: string }>; deals: Array<{ id: string }> }) | null };
type Analytics = { inboundToday: number; outboundToday: number; unread: number; failed: number; linked: number; unknown: number; averageFirstResponseMinutes: number | null };

const FILTERS = [["mine", "Mine"], ["unassigned", "Unassigned"], ["unread", "Unread"], ["linked", "Linked"], ["unknown", "Unknown"], ["all", "All"]] as const;

export function WhatsAppInbox({ currentUser }: { currentUser: { id: string; role: UserRole } }) {
  const [conversations, setConversations] = useState<Conversation[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [options, setOptions] = useState<Options | null>(null);
  const [messageCursor, setMessageCursor] = useState<string | null>(null);
  const [analytics, setAnalytics] = useState<Analytics | null>(null); const [referenceNow] = useState(() => Date.now());
  const [filter, setFilter] = useState("all"); const [search, setSearch] = useState(""); const [draft, setDraft] = useState(""); const [kind, setKind] = useState("text"); const [choice, setChoice] = useState(""); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState("");

  const loadConversations = useCallback(async () => {
    setLoading(true); const res = await fetch(`/api/whatsapp/inbox?filter=${filter}&search=${encodeURIComponent(search)}`); const data = await res.json();
    if (res.ok) { setConversations(data.conversations); setSelectedId((id) => id && data.conversations.some((c: Conversation) => c.id === id) ? id : data.conversations[0]?.id ?? null); } else setError(data.error); setLoading(false);
  }, [filter, search]);
  const openConversation = useCallback(async (id: string) => {
    setSelectedId(id); setError("");
    const [m, d] = await Promise.all([fetch(`/api/whatsapp/inbox/${id}/messages`), fetch(`/api/whatsapp/inbox/${id}`)]); const [md, dd] = await Promise.all([m.json(), d.json()]);
    if (m.ok && d.ok) { setMessages(md.messages); setMessageCursor(md.nextCursor); setDetail(dd.conversation); await fetch(`/api/whatsapp/inbox/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "read" }) }); }
  }, []);
  useEffect(() => { const timer = setTimeout(() => void loadConversations(), 200); return () => clearTimeout(timer); }, [loadConversations]);
  useEffect(() => { Promise.all([fetch("/api/whatsapp/inbox/options").then((r) => r.json()), fetch("/api/whatsapp/inbox/analytics").then((r) => r.json())]).then(([o, a]) => { setOptions(o); setAnalytics(a); }).catch(() => setError("Could not load inbox options")); }, []);
  useEffect(() => { if (!selectedId) return; const timer = setTimeout(() => void openConversation(selectedId), 0); return () => clearTimeout(timer); }, [selectedId, openConversation]);

  const withinWindow = detail?.lastInboundAt ? referenceNow - new Date(detail.lastInboundAt).getTime() <= 24 * 60 * 60 * 1000 : false;
  const availableChoices = useMemo(() => kind === "catalogue" ? options?.catalogues.filter((c) => c.leadId === detail?.leadId) : kind === "property" ? options?.properties : kind === "template" ? options?.templates.filter((t) => t.approved) : [], [kind, options, detail?.leadId]);
  async function sendMessage() {
    if (!selectedId) return; setSending(true); setError("");
    const payload = { kind, content: draft, templateName: kind === "template" ? choice : undefined, catalogueId: kind === "catalogue" ? choice : undefined, propertyId: kind === "property" ? choice : undefined };
    const res = await fetch(`/api/whatsapp/inbox/${selectedId}/messages`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(payload) }); const data = await res.json();
    if (!res.ok) setError(data.error); else { setDraft(""); setChoice(""); await openConversation(selectedId); await loadConversations(); } setSending(false);
  }
  async function patch(action: string, value?: string) {
    if (!selectedId) return; const body = action === "assign" ? { action, assignedToId: value || null } : action === "link" ? { action, leadId: value } : { action };
    const res = await fetch(`/api/whatsapp/inbox/${selectedId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    if (res.ok) { await openConversation(selectedId); await loadConversations(); } else setError((await res.json()).error);
  }
  async function retry(messageId: string) {
    if (!detail?.leadId) return;
    const res = await fetch(`/api/leads/${detail.leadId}/whatsapp/messages/${messageId}/retry`, { method: "POST" });
    if (res.ok && selectedId) await openConversation(selectedId); else setError((await res.json()).error);
  }
  async function loadOlder() {
    if (!selectedId || !messageCursor) return;
    const res = await fetch(`/api/whatsapp/inbox/${selectedId}/messages?cursor=${encodeURIComponent(messageCursor)}`); const data = await res.json();
    if (res.ok) { setMessages((current) => [...data.messages, ...current]); setMessageCursor(data.nextCursor); } else setError(data.error);
  }

  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-[#1B2430]">WhatsApp Inbox</h1><p className="text-sm text-[#596579]">Human-controlled client conversations · {options?.provider ?? "…"}</p></div><button onClick={() => void loadConversations()} className="rounded-lg border px-3 py-2 text-sm"><RefreshCw className="inline h-4 w-4" /> Refresh</button></div>
    {analytics && <div className="grid grid-cols-2 gap-2 text-sm md:grid-cols-4 lg:grid-cols-7">{[["Inbound today", analytics.inboundToday], ["Outbound today", analytics.outboundToday], ["Unread", analytics.unread], ["Failed", analytics.failed], ["Linked", analytics.linked], ["Unknown", analytics.unknown], ["Avg response", analytics.averageFirstResponseMinutes == null ? "—" : `${analytics.averageFirstResponseMinutes}m`]].map(([label, value]) => <div key={String(label)} className="rounded-xl border bg-white p-3"><p className="text-xs text-slate-500">{label}</p><strong>{value}</strong></div>)}</div>}
    <div className="grid min-h-[70vh] overflow-hidden rounded-2xl border bg-white shadow-sm lg:grid-cols-[300px_minmax(360px,1fr)_300px]">
      <aside className={`${selectedId ? "hidden lg:block" : "block"} border-r`}><div className="border-b p-3"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input aria-label="Search conversations" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Name, phone, lead code" className="w-full rounded-lg border py-2 pl-9 pr-3 text-sm"/></div><div className="mt-2 flex flex-wrap gap-1">{FILTERS.map(([v,l]) => <button key={v} onClick={() => setFilter(v)} className={`rounded-full px-2 py-1 text-xs ${filter === v ? "bg-[#3366FF] text-white" : "bg-slate-100"}`}>{l}</button>)}</div></div>
        <div className="max-h-[66vh] overflow-y-auto">{loading ? <Loader2 className="m-6 h-5 w-5 animate-spin"/> : conversations.map((c) => <button key={c.id} onClick={() => setSelectedId(c.id)} className={`w-full border-b p-3 text-left hover:bg-slate-50 ${selectedId === c.id ? "bg-blue-50" : ""}`}><div className="flex justify-between"><span className="truncate font-semibold">{c.lead?.clientName ?? c.displayName ?? "Unknown Contact"}</span>{c.unreadCount > 0 && <span className="rounded-full bg-green-600 px-2 text-xs text-white">{c.unreadCount}</span>}</div><p className="text-xs text-slate-500">{c.phoneNumber} · {c.contactState === "AMBIGUOUS" ? "Multiple possible leads" : c.contactState}</p><p className="mt-1 truncate text-sm text-slate-600">{c.messages[0]?.content ?? "No messages"}</p></button>)}</div>
      </aside>
          <main className={`${!selectedId ? "hidden lg:flex" : "flex"} min-w-0 flex-col`}>
        {!selectedId ? <div className="m-auto text-center text-slate-500"><MessageCircle className="mx-auto mb-2 h-10 w-10"/>Choose a conversation</div> : <><header className="flex items-center justify-between border-b p-3"><div><button className="mr-2 lg:hidden" onClick={() => setSelectedId(null)}>←</button><strong>{detail?.lead?.clientName ?? detail?.displayName ?? "Unknown Contact"}</strong><p className="text-xs text-slate-500">{withinWindow ? "Within 24-hour service window" : "Template required outside 24 hours"}</p></div>{(detail?.unreadCount ?? 0) > 0 && <span className="text-xs text-green-700">Marked read in CRM</span>}</header>
          <div className="flex-1 space-y-2 overflow-y-auto bg-slate-50 p-4">{messageCursor && <div className="text-center"><button onClick={() => void loadOlder()} className="rounded-full border bg-white px-3 py-1 text-xs">Load older messages</button></div>}{messages.map((m) => <div key={m.id} className={`max-w-[80%] rounded-xl p-3 text-sm shadow-sm ${m.direction === "OUTBOUND" ? "ml-auto bg-green-100" : "bg-white"}`}><p className="mb-1 text-[10px] uppercase text-slate-500">{m.messageType}</p><p className="whitespace-pre-wrap">{m.content}</p>{m.mediaFilename && <p className="mt-1 text-xs">📎 {m.mediaFilename} (private)</p>}<div className="mt-1 flex justify-end gap-1 text-[10px] text-slate-500">{new Date(m.createdAt).toLocaleString()}{m.status === "READ" || m.status === "DELIVERED" ? <CheckCheck className={`h-3 w-3 ${m.status === "READ" ? "text-blue-600" : ""}`}/> : m.status === "FAILED" ? <AlertCircle className="h-3 w-3 text-red-600"/> : null}</div>{m.status === "FAILED" && <div className="mt-1 text-xs text-red-700">{m.errorMessage ?? "Delivery failed"} <button onClick={() => void retry(m.id)} className="font-semibold underline">Retry manually</button></div>}</div>)}</div>
          <footer className="border-t p-3">{error && <p role="alert" className="mb-2 text-sm text-red-700">{error}</p>}<div className="mb-2 flex gap-2"><select aria-label="Message type" value={kind} onChange={(e) => { setKind(e.target.value); setChoice(""); }} className="rounded-lg border p-2 text-sm"><option value="text">Text</option><option value="catalogue">Catalogue</option><option value="property">Property</option><option value="template">Approved template</option></select>{kind !== "text" && <select aria-label="Select content" value={choice} onChange={(e) => setChoice(e.target.value)} className="min-w-0 flex-1 rounded-lg border p-2 text-sm"><option value="">Select…</option>{availableChoices?.map((o) => { const id = "id" in o ? o.id : o.name; const label = "title" in o ? o.title : o.useCase; return <option key={id} value={id}>{label}</option>; })}</select>}</div><div className="flex gap-2"><textarea aria-label="Message" value={draft} onChange={(e) => setDraft(e.target.value)} placeholder={kind === "text" ? "Type a reply…" : "Optional message"} disabled={!withinWindow && kind !== "template" && options?.provider === "META_CLOUD"} className="min-h-12 flex-1 resize-none rounded-lg border p-2 text-sm"/><button aria-label="Send explicitly" onClick={() => void sendMessage()} disabled={sending || !detail?.leadId || (kind !== "text" && !choice)} className="rounded-lg bg-[#3366FF] px-4 text-white disabled:opacity-40">{sending ? <Loader2 className="h-4 w-4 animate-spin"/> : <Send className="h-4 w-4"/>}</button></div>{!detail?.leadId && <p className="mt-1 text-xs text-amber-700">Link a lead before sending. No message is sent automatically.</p>}</footer></>}
      </main>
          <aside className="hidden border-l p-4 lg:block"><h2 className="font-semibold">CRM context</h2>{detail ? <div className="mt-4 space-y-4 text-sm"><div><p className="text-xs text-slate-500">Contact</p><p>{detail.lead?.clientName ?? detail.displayName ?? "Unknown Contact"}</p><p className="text-slate-500">{detail.phoneNumber}</p></div>{detail.lead ? <><Link href={`/leads/${detail.lead.id}`} className="text-blue-600">Open Lead →</Link><p>Status: {detail.lead.status}</p><p>Requirement: {detail.lead.requirementType} · {detail.lead.preferredLocation}</p><div className="flex flex-wrap gap-2"><Link href={`/follow-ups?leadId=${detail.lead.id}`} className="text-blue-600">Schedule Follow-up</Link><Link href={`/visits?leadId=${detail.lead.id}`} className="text-blue-600">Create Visit</Link></div>{detail.lead.catalogueShares?.[0] && <Link href={`/leads/${detail.lead.id}`} className="block text-blue-600">Open latest catalogue v{detail.lead.catalogueShares[0].version}</Link>}{detail.lead.visits?.[0] && <p>Upcoming visit: {new Date(detail.lead.visits[0].visitDate).toLocaleString()}</p>}{detail.lead.deals?.[0] && <Link href={`/deals/${detail.lead.deals[0].id}`} className="block text-blue-600">Open active deal</Link>}{currentUser.role !== "FIELD_EXECUTIVE" && <button onClick={() => void patch("unlink")} className="text-red-600">Unlink conversation</button>}</> : currentUser.role !== "FIELD_EXECUTIVE" ? <div className="space-y-2"><select aria-label="Link lead" onChange={(e) => e.target.value && void patch("link", e.target.value)} className="w-full rounded border p-2"><option value="">Link to existing lead…</option>{options?.leads.map((l) => <option key={l.id} value={l.id}>{l.clientName} · {l.leadCode}</option>)}</select><Link className="block text-blue-600" href={`/leads/new?phone=${encodeURIComponent(detail.phoneNumber)}`}><Link2 className="inline h-4 w-4"/> Create New Lead</Link></div> : null}{currentUser.role !== "FIELD_EXECUTIVE" && <select aria-label="Assign conversation" value={detail.assignedToId ?? ""} onChange={(e) => void patch("assign", e.target.value)} className="w-full rounded border p-2"><option value="">Unassigned</option>{options?.employees.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</select>}<div className="rounded-lg bg-blue-50 p-3 text-xs"><UserRound className="mb-1 h-4 w-4"/>Assignment changes and link changes are audited.</div></div> : <Clock3 className="mt-4 h-5 w-5 animate-pulse"/>}</aside>
    </div>
  </div>;
}
