import { auth } from "@/lib/auth";
import { getPhase5Analytics } from "@/lib/phase5-analytics";
import { KpiCard } from "@/components/ui/kpi-card";
import { BarChartCard, PieChartCard } from "@/components/dashboard/charts";
import { Building2, Clock, Trophy, XCircle } from "lucide-react";

export default async function Phase5ReportsPage() {
  const session = await auth(); const data = await getPhase5Analytics(session!.user.id);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Demand & Negotiation Intelligence</h1><p className="text-sm text-[#596579]">Internal pipeline analytics only; no payment collection metrics.</p></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><KpiCard label="Active Negotiations" value={data.negotiation.activeNegotiations} icon={Building2} tone="indigo"/><KpiCard label="Agreement Pending" value={data.negotiation.agreementPending} icon={Clock} tone="blue"/><KpiCard label="Won This Month" value={data.negotiation.won} icon={Trophy} tone="green"/><KpiCard label="Lost This Month" value={data.negotiation.lost} icon={XCircle} tone="red"/></div><div className="grid gap-4 lg:grid-cols-2"><BarChartCard title="Demand by Locality" data={data.demand.byLocality}/><BarChartCard title="Demand by BHK" data={data.demand.byBhk}/><BarChartCard title="Demand by Budget" data={data.demand.byBudget}/><PieChartCard title="Rent vs Sale Demand" data={data.demand.rentVsSale}/></div><div className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border p-4"><b>{data.demand.zeroInventory}</b><p>Requirements with zero inventory</p></div><div className="rounded-xl border p-4"><b>{data.demand.avgFirstMatchDays} days</b><p>Average time to first match</p></div><div className="rounded-xl border p-4"><b>₹{data.negotiation.expectedBrokeragePipeline.toLocaleString("en-IN")}</b><p>Expected brokerage pipeline</p></div></div><div className="rounded-xl border p-4"><h2 className="font-semibold">Demand / Supply Gap</h2>{data.demand.demandSupplyGap.map(g => <p className="mt-2 text-sm" key={g.locality}>{g.locality}: {g.demand} requirements / {g.supply} properties · <b>{g.level}</b></p>)}</div><div className="rounded-xl border p-4"><h2 className="font-semibold">Negotiation Summary</h2><p>Stale: {data.negotiation.staleNegotiations} · Win/loss ratio: {data.negotiation.winLossRatio}% · Avg duration: {data.negotiation.avgNegotiationDays} days</p><p>Direct: {data.negotiation.directCount} · Indirect: {data.negotiation.indirectCount}</p></div></div>;
}
