import {
  UserPlus,
  UserCog,
  ArrowRightLeft,
  BellRing,
  AlertTriangle,
  CalendarClock,
  CalendarX,
  CalendarCog,
  Share2,
  MessageCircle,
  Trophy,
  Wallet,
  Users,
  Eye,
  ThumbsUp,
  ThumbsDown,
  CalendarPlus,
  HelpCircle,
  XCircle,
  UserX,
  Users2,
  Settings2,
  Sparkles,
  SearchX,
  ClipboardCheck,
  SendHorizonal,
  Building2,
  IndianRupee,
  UserRoundX,
  MailWarning,
  CalendarOff,
  ImageOff,
  Handshake,
  FileClock,
  type LucideIcon,
} from "lucide-react";
import type { Notification, NotificationType } from "@prisma/client";

export const NOTIFICATION_ICONS: Record<NotificationType, LucideIcon> = {
  NEW_LEAD: UserPlus,
  LEAD_ASSIGNED: UserCog,
  LEAD_TRANSFERRED: ArrowRightLeft,
  FOLLOW_UP_DUE: BellRing,
  FOLLOW_UP_OVERDUE: AlertTriangle,
  VISIT_SCHEDULED: CalendarClock,
  VISIT_RESCHEDULED: CalendarCog,
  VISIT_CANCELLED: CalendarX,
  PROPERTY_SHARED: Share2,
  CLIENT_REPLY_RECEIVED: MessageCircle,
  DEAL_WON: Trophy,
  PAYMENT_PENDING: Wallet,
  EMPLOYEE_CAPACITY_REACHED: Users,
  CATALOGUE_VIEWED: Eye,
  PROPERTY_INTERESTED: ThumbsUp,
  PROPERTY_NOT_INTERESTED: ThumbsDown,
  VISIT_REQUESTED: CalendarPlus,
  QUESTION_ASKED: HelpCircle,
  WHATSAPP_MESSAGE_FAILED: XCircle,
  WHATSAPP_UNKNOWN_CONTACT: UserX,
  WHATSAPP_MULTIPLE_LEAD_MATCH: Users2,
  WHATSAPP_TEMPLATE_CONFIG_ISSUE: Settings2,
  MATCHES_READY: Sparkles,
  NO_MATCHES_FOUND: SearchX,
  CATALOGUE_READY_FOR_REVIEW: ClipboardCheck,
  CATALOGUE_SENT: SendHorizonal,
  PROPERTY_UNAVAILABLE_AFTER_SHARE: Building2,
  PROPERTY_PRICE_CHANGED_AFTER_SHARE: IndianRupee,
  HOT_LEAD_NO_FOLLOWUP: UserRoundX,
  CATALOGUE_NO_RESPONSE: MailWarning,
  VISIT_MISSED: CalendarOff,
  PROPERTY_MISSING_PHOTOS: ImageOff,
  DEAL_NEGOTIATION_STALE: Handshake,
  DOCUMENT_EXPIRING: FileClock,
};

export const NOTIFICATION_LABELS: Record<NotificationType, string> = {
  NEW_LEAD: "New Lead",
  LEAD_ASSIGNED: "Lead Assigned",
  LEAD_TRANSFERRED: "Lead Transferred",
  FOLLOW_UP_DUE: "Follow-up Due",
  FOLLOW_UP_OVERDUE: "Follow-up Overdue",
  VISIT_SCHEDULED: "Visit Scheduled",
  VISIT_RESCHEDULED: "Visit Rescheduled",
  VISIT_CANCELLED: "Visit Cancelled",
  PROPERTY_SHARED: "Property Shared",
  CLIENT_REPLY_RECEIVED: "Client Reply",
  DEAL_WON: "Deal Won",
  PAYMENT_PENDING: "Payment Pending",
  EMPLOYEE_CAPACITY_REACHED: "Capacity Reached",
  CATALOGUE_VIEWED: "Catalogue Viewed",
  PROPERTY_INTERESTED: "Property Interested",
  PROPERTY_NOT_INTERESTED: "Property Not Interested",
  VISIT_REQUESTED: "Visit Requested",
  QUESTION_ASKED: "Question Asked",
  WHATSAPP_MESSAGE_FAILED: "Message Failed",
  WHATSAPP_UNKNOWN_CONTACT: "Unknown WhatsApp Contact",
  WHATSAPP_MULTIPLE_LEAD_MATCH: "Multiple Lead Match",
  WHATSAPP_TEMPLATE_CONFIG_ISSUE: "Template Configuration Issue",
  MATCHES_READY: "Matches Ready",
  NO_MATCHES_FOUND: "No Matches Found",
  CATALOGUE_READY_FOR_REVIEW: "Catalogue Ready for Review",
  CATALOGUE_SENT: "Catalogue Sent",
  PROPERTY_UNAVAILABLE_AFTER_SHARE: "Property Unavailable After Share",
  PROPERTY_PRICE_CHANGED_AFTER_SHARE: "Property Price Changed After Share",
  HOT_LEAD_NO_FOLLOWUP: "Hot Lead - No Follow-up",
  CATALOGUE_NO_RESPONSE: "Catalogue - No Response",
  VISIT_MISSED: "Visit Missed",
  PROPERTY_MISSING_PHOTOS: "Property Missing Photos",
  DEAL_NEGOTIATION_STALE: "Negotiation Stalled",
  DOCUMENT_EXPIRING: "Document Expiring",
};

export function notificationHref(n: Notification): string | null {
  if (n.leadId) return `/leads/${n.leadId}`;
  if (n.propertyId) return `/properties/${n.propertyId}`;
  return null;
}
