"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

type Recommendation = { id: string; score: number; property: { id: string; propertyCode: string; title: string; area: string; bhk: number; monthlyRent: number | null; salePrice: number | null; listingType: string; inventorySource: string; status: string; coverImage: string | null; lastVerifiedAt: Date | null; pendingVerification: boolean } };
type Catalogue = { id: string; title: string; version: number };

export function NewMatchesPanel({ leadId, recommendations, catalogues, canManage, providerSendConfigured }: { leadId: string; recommendations: Recommendation[]; catalogues: Catalogue[]; canManage: boolean; providerSendConfigured: boolean }) {
  const router = useRouter(); const [selected, setSelected] = useState<string[]>([]); const [catalogueId, setCatalogueId] = useState(catalogues[0]?.id ?? ""); const [suggestion, setSuggestion] = useState("");
  const selectedSet = useMemo(() => new Set(selected), [selected]);
  if (!recommendations.length) return null;
  async function ignore(ids: string[]) { const res = await fetch("/api/match-recommendations", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recommendationIds: ids, action: "IGNORE" }) }); if (res.ok) { toast.success("Match ignored"); router.refresh(); } else toast.error("Could not ignore match"); }
  async function approve(ids: string[]) { if (!catalogueId) return toast.error("Create or select an active catalogue first"); const res = await fetch("/api/match-recommendations/approve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ catalogueId, recommendationIds: ids }) }); const data = await res.json(); if (res.ok) { setSuggestion(data.suggestedWhatsAppMessage); toast.success(`${data.added} properties added in catalogue v${data.version}`); router.refresh(); } else toast.error(data.error ?? "Approval failed"); }
  async function sendExplicitly() { const res = await fetch(`/api/leads/${leadId}/whatsapp/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: suggestion, messageType: "TEXT" }) }); if (res.ok) toast.success("WhatsApp message sent by your explicit action"); else toast.error("Provider send failed"); }
  return <section className="rounded-2xl border border-blue-200 bg-blue-50/40 p-5 space-y-4"><div className="flex items-center justify-between"><h3 className="font-bold">NEW MATCHES · {recommendations.length}</h3>{canManage && <div className="flex gap-2"><select className="border rounded px-2" value={catalogueId} onChange={e => setCatalogueId(e.target.value)}>{catalogues.map(c => <option key={c.id} value={c.id}>{c.title} · V{c.version}</option>)}</select><button className="border rounded px-2" onClick={() => approve(selected)}>Add Selected</button><button className="border rounded px-2" onClick={() => ignore(selected)}>Ignore Selected</button></div>}</div><div className="grid gap-3 md:grid-cols-2">{recommendations.map(r => { const p = r.property; const price = p.listingType === "RENT" ? p.monthlyRent : p.salePrice; const warnings = [!p.coverImage && "No photo", p.pendingVerification && "Pending verification", !p.lastVerifiedAt && "Not recently verified"].filter(Boolean); return <article key={r.id} className="rounded-xl border bg-white p-3"><label className="flex gap-3"><input type="checkbox" checked={selectedSet.has(r.id)} onChange={e => setSelected(v => e.target.checked ? [...v, r.id] : v.filter(x => x !== r.id))}/><div className="flex-1"><p className="font-semibold">{p.propertyCode} · {r.score}%</p><p className="text-sm">{p.bhk} BHK · {p.area} · ₹{price?.toLocaleString("en-IN") ?? "—"}</p><p className="text-xs">{p.inventorySource} · {p.status}</p>{warnings.map(w => <span key={String(w)} className="mr-1 text-xs text-amber-700">{w}</span>)}</div></label><div className="mt-2 flex gap-2 text-sm"><Link href={`/properties/${p.id}`} className="text-blue-700">View</Link>{canManage && <><button onClick={() => approve([r.id])}>Add</button><button onClick={() => ignore([r.id])}>Ignore</button></>}</div></article>; })}</div>{suggestion && <div className="rounded-xl border bg-white p-3"><p className="font-semibold">Catalogue updated. Send client an update?</p><textarea className="mt-2 w-full border rounded p-2" rows={8} value={suggestion} onChange={e => setSuggestion(e.target.value)}/><div className="mt-2 flex gap-2"><button className="border rounded px-3 py-1" onClick={() => navigator.clipboard.writeText(suggestion)}>Copy</button><a className="border rounded px-3 py-1" href={`https://wa.me/?text=${encodeURIComponent(suggestion)}`} target="_blank" rel="noreferrer">Open WhatsApp</a>{providerSendConfigured && <button className="rounded bg-green-700 px-3 py-1 text-white" onClick={sendExplicitly}>Send via provider</button>}</div><p className="mt-1 text-xs text-[#596579]">No message was sent automatically. Provider send is available only when configured and only runs after clicking Send.</p></div>}</section>;
}
