import { notFound } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getOrganizationId } from "@/lib/organization";
import { DealActions } from "@/components/deals/deal-actions";

export default async function DealPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const session = await auth(); const commercial = session!.user.role !== "FIELD_EXECUTIVE"; const deal = await prisma.deal.findFirst({ where: { id, organizationId: getOrganizationId(session!.user.id), ...(session!.user.role === "FIELD_EXECUTIVE" ? { assignedToId: session!.user.id } : {}) }, include: { lead: true, property: { include: { partner: true } }, owner: true, assignedTo: true, offers: { include: { createdBy: { select: { name: true } } }, orderBy: { createdAt: "asc" } }, activities: { orderBy: { createdAt: "desc" }, take: 100 }, brokerageCalculations: commercial } }); if (!deal) notFound();
  return <div className="space-y-6"><header><h1 className="text-2xl font-bold">{deal.dealCode} · {deal.lead?.clientName}</h1><p className="text-sm text-[#596579]">{deal.property?.title} · {deal.property?.inventorySource}{deal.property?.partner ? ` · ${deal.property.partner.name}` : ""}</p></header><section className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border p-4"><h2 className="font-semibold">Negotiation</h2><p className="mt-2">Current stage: <b>{deal.stage}</b></p><p>Next follow-up: {deal.lead?.nextFollowUpAt?.toLocaleDateString() ?? "Not scheduled"}</p>{deal.status === "LOST" && <p className="mt-2 text-red-700">Lost: {deal.lostReasonCategory} — {deal.lostReason}</p>}</div>{commercial && <div className="rounded-xl border p-4"><h2 className="font-semibold">Internal commercial terms</h2><p>Expected brokerage: ₹{deal.expectedBrokerageAmount?.toLocaleString("en-IN") ?? "—"}</p><p>KP share: {deal.kpSharePct ?? "—"}% · Partner share: {deal.partnerSharePct ?? "—"}%</p></div>}</section><DealActions dealId={deal.id} indirect={deal.property?.inventorySource === "INDIRECT"} canManage={commercial}/><section className="rounded-xl border p-4"><h2 className="font-semibold">Offer / Counter-offer history</h2><ol className="mt-3 space-y-2">{deal.offers.map(o => <li key={o.id} className="border-l-2 pl-3"><b>{o.side}</b> · ₹{o.amount.toLocaleString("en-IN")} <span className="text-xs text-[#596579]">{o.createdAt.toLocaleString()} by {o.createdBy.name}</span>{commercial && o.note ? <div>{o.note}</div> : null}</li>)}</ol></section><section className="rounded-xl border p-4"><h2 className="font-semibold">Timeline</h2>{deal.activities.map(a => <p key={a.id} className="mt-2 text-sm">{a.createdAt.toLocaleString()} — {a.description}</p>)}</section></div>;
}
