import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getOrganizationId } from "@/lib/organization";
import { matchPropertiesToLead } from "@/lib/matching";

export default async function RequirementsPage() {
  const session = await auth(); const organizationId = getOrganizationId(session!.user.id);
  const [leads, properties] = await Promise.all([prisma.lead.findMany({ where: { organizationId, status: { notIn: ["CLOSED_WON", "CLOSED_LOST", "INVALID"] } }, include: { assignedTo: { select: { name: true } }, requirementBroadcasts: { orderBy: { createdAt: "desc" }, take: 1 }, matchRecommendations: { where: { status: "PENDING" }, select: { id: true } } }, take: 250, orderBy: { createdAt: "asc" } }), prisma.property.findMany({ where: { organizationId, status: "AVAILABLE" }, take: 1000 })]);
  const rows = leads.map(lead => { const matchCount = matchPropertiesToLead(properties, lead).length; return { lead, matchCount, status: matchCount === 0 ? "NO_MATCHES" : matchCount <= 2 ? "LIMITED_MATCHES" : "MATCHES_AVAILABLE" }; });
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Requirement Board</h1><p className="text-sm text-[#596579]">Use broadcasts to source inventory; messages are prepared for manual sharing only.</p></div><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-[#FAFBFC] text-left"><tr><th className="p-3">Client</th><th className="p-3">Requirement</th><th className="p-3">Matches</th><th className="p-3">Broadcast</th><th className="p-3">New matches</th><th className="p-3">Assigned</th></tr></thead><tbody>{rows.map(({ lead, matchCount, status }) => <tr className="border-t" key={lead.id}><td className="p-3 font-medium">{lead.clientName}<div className="text-xs text-[#596579]">{lead.createdAt.toLocaleDateString()}</div></td><td className="p-3">{lead.preferredBhk ?? "Any"} BHK · {lead.preferredLocation}<div className="text-xs">₹{lead.minBudget.toLocaleString("en-IN")}–₹{lead.maxBudget.toLocaleString("en-IN")} · {lead.requirementType}</div></td><td className="p-3"><b>{matchCount}</b><div className={status === "NO_MATCHES" ? "text-red-700 text-xs" : "text-xs"}>{status}</div></td><td className="p-3">{lead.requirementBroadcasts[0]?.status ?? "Not broadcast"}</td><td className="p-3">{lead.matchRecommendations.length}</td><td className="p-3">{lead.assignedTo?.name ?? "Unassigned"}</td></tr>)}</tbody></table></div></div>;
}
