-- Property business foundation: additive, no production application by this change.
CREATE TYPE "AssetClass" AS ENUM ('RESIDENTIAL', 'COMMERCIAL');
CREATE TYPE "TransactionType" AS ENUM ('RENT', 'SALE');
CREATE TYPE "CommercialFitOut" AS ENUM ('FURNISHED', 'SEMI_FURNISHED', 'BARE_SHELL');
CREATE TYPE "PropertyPortalProvider" AS ENUM ('HOUSING', 'NINETY_NINE_ACRES', 'MAGICBRICKS', 'OLX', 'SQUARE_CONNECT', 'OTHER');
CREATE TYPE "PortalConnectionStatus" AS ENUM ('CONNECTED', 'NOT_CONFIGURED', 'DEGRADED', 'AUTH_FAILED', 'PARTNER_ACCESS_REQUIRED');
CREATE TYPE "PortalConnectionMode" AS ENUM ('API', 'WEBHOOK', 'CSV', 'EMAIL', 'MANUAL');
CREATE TYPE "PortalListingStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'INACTIVE', 'SYNC_CONFLICT', 'FAILED');
CREATE TYPE "PortalIngestionStatus" AS ENUM ('NEW', 'RECEIVED', 'MATCHED_EXISTING', 'AMBIGUOUS', 'DUPLICATE', 'NEEDS_REVIEW', 'REJECTED', 'FAILED');
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'STUDIO'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'FARM_HOUSE'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'CO_LIVING'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'OTHER'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'OFFICE'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'SHOP'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'SHOWROOM'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'WAREHOUSE'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'INDUSTRIAL'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'COMMERCIAL_LAND'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'CO_WORKING'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'RESTAURANT_SPACE'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'SCO'; ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'OTHER_COMMERCIAL';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'OLX'; ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'SQUARE_CONNECT'; ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'DIRECT'; ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'OTHER';
ALTER TABLE "properties" ADD COLUMN "assetClass" "AssetClass" NOT NULL DEFAULT 'RESIDENTIAL', ADD COLUMN "superAreaSqft" INTEGER, ADD COLUMN "frontageFeet" DOUBLE PRECISION, ADD COLUMN "ceilingHeightFeet" DOUBLE PRECISION, ADD COLUMN "cabins" INTEGER, ADD COLUMN "workstations" INTEGER, ADD COLUMN "washrooms" INTEGER, ADD COLUMN "pantryAvailable" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "powerLoadKw" DOUBLE PRECISION, ADD COLUMN "commercialFitOut" "CommercialFitOut", ADD COLUMN "goodsLiftAvailable" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "loadingAccessAvailable" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "roadWidthFeet" DOUBLE PRECISION, ADD COLUMN "cornerProperty" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "fireSafetyAvailable" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "suitableForTags" TEXT NOT NULL DEFAULT '[]', ADD COLUMN "leaseTermMonths" INTEGER, ADD COLUMN "lockInPeriodMonths" INTEGER, ADD COLUMN "noticePeriodMonths" INTEGER, ADD COLUMN "escalationPercentage" DOUBLE PRECISION, ADD COLUMN "escalationIntervalMonths" INTEGER, ADD COLUMN "fitOutPeriodDays" INTEGER, ADD COLUMN "camCharge" INTEGER, ADD COLUMN "expectedPrice" INTEGER, ADD COLUMN "ownershipTitleNotes" TEXT;
ALTER TABLE "leads" ADD COLUMN "assetClass" "AssetClass" NOT NULL DEFAULT 'RESIDENTIAL', ADD COLUMN "transactionType" "TransactionType" NOT NULL DEFAULT 'RENT', ADD COLUMN "portalProvider" "PropertyPortalProvider", ADD COLUMN "externalListingId" TEXT, ADD COLUMN "rawPayloadHash" TEXT, ADD COLUMN "receivedAt" TIMESTAMP(3), ADD COLUMN "commercialPropertyType" "PropertyType", ADD COLUMN "minAreaSqft" INTEGER, ADD COLUMN "maxAreaSqft" INTEGER, ADD COLUMN "floorPreference" TEXT, ADD COLUMN "commercialFitOutPref" "CommercialFitOut", ADD COLUMN "parkingRequired" BOOLEAN, ADD COLUMN "liftRequired" BOOLEAN, ADD COLUMN "suitableForTags" TEXT NOT NULL DEFAULT '[]';
UPDATE "leads" SET "transactionType" = CASE WHEN "requirementType" = 'BUY' THEN 'SALE'::"TransactionType" ELSE 'RENT'::"TransactionType" END;
CREATE TABLE "property_portal_connections" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL DEFAULT 'org_default', "provider" "PropertyPortalProvider" NOT NULL, "status" "PortalConnectionStatus" NOT NULL DEFAULT 'NOT_CONFIGURED', "connectionMode" "PortalConnectionMode" NOT NULL DEFAULT 'MANUAL', "displayName" TEXT, "accountReference" TEXT, "credentialReference" TEXT, "config" TEXT NOT NULL DEFAULT '{}', "lastSyncAt" TIMESTAMP(3), "lastSuccessfulSyncAt" TIMESTAMP(3), "lastErrorAt" TIMESTAMP(3), "lastErrorSummary" TEXT, "createdById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE);
CREATE TABLE "portal_listings" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL DEFAULT 'org_default', "connectionId" TEXT, "propertyId" TEXT NOT NULL, "provider" "PropertyPortalProvider" NOT NULL, "externalListingId" TEXT, "externalUrl" TEXT, "status" "PortalListingStatus" NOT NULL DEFAULT 'DRAFT', "publishedAt" TIMESTAMP(3), "lastSyncedAt" TIMESTAMP(3), "payloadHash" TEXT, "errorSummary" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE, FOREIGN KEY ("connectionId") REFERENCES "property_portal_connections"("id") ON DELETE SET NULL, FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE CASCADE);
CREATE TABLE "external_lead_events" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL DEFAULT 'org_default', "connectionId" TEXT, "portalListingId" TEXT, "leadId" TEXT, "provider" "PropertyPortalProvider" NOT NULL, "externalLeadId" TEXT, "externalEventId" TEXT, "externalListingId" TEXT, "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "message" TEXT, "rawPayloadHash" TEXT NOT NULL, "ingestionStatus" "PortalIngestionStatus" NOT NULL DEFAULT 'NEW', "failureReason" TEXT, "attemptCount" INTEGER NOT NULL DEFAULT 0, "lastAttemptAt" TIMESTAMP(3), "resolvedAt" TIMESTAMP(3), "resolvedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE, FOREIGN KEY ("connectionId") REFERENCES "property_portal_connections"("id") ON DELETE SET NULL, FOREIGN KEY ("portalListingId") REFERENCES "portal_listings"("id") ON DELETE SET NULL, FOREIGN KEY ("leadId") REFERENCES "leads"("id") ON DELETE SET NULL);
CREATE INDEX "properties_organizationId_assetClass_listingType_idx" ON "properties"("organizationId", "assetClass", "listingType"); CREATE INDEX "leads_organizationId_assetClass_transactionType_idx" ON "leads"("organizationId", "assetClass", "transactionType"); CREATE UNIQUE INDEX "portal_listings_organizationId_provider_externalListingId_key" ON "portal_listings"("organizationId", "provider", "externalListingId"); CREATE UNIQUE INDEX "external_lead_events_organizationId_provider_externalEventId_key" ON "external_lead_events"("organizationId", "provider", "externalEventId");
